service: dynamodb

frameworkVersion: ^2.15.0

package:
  individually: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-offline-dynamodb-streams

provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  logRetentionInDays: 5
  #tracing:
  #  lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: '*'
  #tags:
  #  commit: '${env:COMMIT_ID}'

custom:
  serverless-offline-dynamodb-streams:
    apiVersion: '2013-12-02'
    endpoint: http://0.0.0.0:8000
    region: us-east-1
    accessKeyId: x
    secretAccessKey: x
    skipCacheInvalidation: false
    readInterval: 500

functions:
  trigger:
    timeout: 6
    memorySize: 128
    handler: index.trigger
    iamRoleStatementsName: ${self:service.name}-${self:provider.stage}-trigger
    iamRoleStatementsInherit: true
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [dynamodb, StreamArn]
          batchSize: 1
          batchWindow: 1
          bisectBatchOnFunctionError: true
          startingPosition: LATEST

resources:
  Resources:
    dynamodb: ${file(./dynamodb.yml)}
