service: apigw-2

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  httpApi:
    payload: '1.0'
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  logRetentionInDays: 5

functions:
  hello:
    timeout: 6
    memorySize: 128
    handler: handler.catchAll
    events:
      - httpApi: '*'
