service: apigw-2

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  httpApi:
    payload: '1.0'

functions:
  hello:
    handler: handler.catchAll
    events:
      - httpApi: '*'
