service: s3-stack

frameworkVersion: ^2.15.0

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-s3-local
provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  logRetentionInDays: 5
  #tracing:
  #  lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: '*'
  #tags:
  #  commit: '${env:COMMIT_ID}'

custom:
  s3:
    host: localhost

functions:
  document:
    timeout: 6
    memorySize: 128
    handler: index.s3
    events:
      - s3:
          bucket: 'document'
          event: s3:ObjectCreated:*
          existing: true
      - s3:
          bucket: 'document'
          event: s3:ObjectRemoved:*
          existing: true
    iamRoleStatementsName: ${self:service.name}-${self:provider.stage}-document"
    iamRoleStatementsInherit: true

resources:
  Resources:
    Document:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 'document'
