service: s3-stack

frameworkVersion: ^2.15

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-s3-local

provider:
  name: aws
  runtime: nodejs12.x

custom:
  s3:
    host: localhost

functions:
  document:
    handler: index.s3
    timeout: 6
    memorySize: 128
    events:
      - s3:
          bucket: 'document'
          event: s3:ObjectCreated:*
          existing: true
      - s3:
          bucket: 'document'
          event: s3:ObjectRemoved:*
          existing: true

resources:
  Resources:
    Document:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 'document'
