service: ws-example

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  logRetentionInDays: 5

  websocketsApiRouteSelectionExpression: $request.body.message

functions:
  handler:
    timeout: 6
    memorySize: 128
    handler: src/index.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: echo
      - websocket: $default
