service: ws-example

package:
  individually: true

frameworkVersion: ^2.15.0

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  stage: dev
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  logRetentionInDays: 5
  #tracing:
  #  lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: '*'
  #tags:
  #  commit: '${env:COMMIT_ID}'

  websocketsApiRouteSelectionExpression: $request.body.message

functions:
  handler:
    timeout: 6
    memorySize: 128
    handler: src/index.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: echo
      - websocket: $default
    iamRoleStatementsName: ${self:service.name}-${self:provider.stage}-ws-example
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "execute-api:ManageConnections"
        Resource:
          - "arn:#{AWS::Partition}:execute-api:#{AWS::Region}:#{AWS::AccountId}:**/@connections/*"
